sudo: required
language: go
go:
  - "1.11.x"
  
sudo: true

matrix:
  include:
    - os: linux
      dist: xenial
      env: VERSION_UPGRADE_TEST_WAIT_TIMEOUT=45s
    - os: osx
      osx_image: xcode8.3
      env: VERSION_UPGRADE_TEST_WAIT_TIMEOUT=60s

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq; fi
  - VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh
  - ./ci-scripts/install-travis-gcc.sh
  - eval "CC=gcc-6 && CXX=g++-6"

env:
  global:
    - BUILD_DIR: build
    - BUILDLIB_DIR: $BUILD_DIR/libskycoin
    - LIB_DIR: lib
    - CGO_ENABLED: 1


install:
  # Install gox
  - go get github.com/gz-c/gox
  - if [[ ! -d $GOPATH/src/github.com/skycoin/libskycoin ]]; then mkdir -p $GOPATH/src/github.com/skycoin; ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/skycoin/libskycoin; fi
  - cd $GOPATH/src/github.com/skycoin/libskycoin
  - pwd
  - go get -t ./...
  - make install-deps-libc
  - make install-linters
  - VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh
  # Install pinned golangci-lint, overriding the latest version install by make install-linters
  - make install-deps-libc
  
  # first we create a directory for the CMake binaries
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  # we use wget to fetch the cmake binaries
  - travis_retry wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz
  # this is optional, but useful:
  # do a quick md5 check to ensure that the archive we downloaded did not get compromised
  - echo "f3546812c11ce7f5d64dc132a566b749 *cmake-3.3.2-Linux-x86_64.tar.gz" > cmake_md5.txt
  - md5sum -c cmake_md5.txt
  # extract the binaries; the output here is quite lengthy,
  # so we swallow it to not clutter up the travis console
  - tar -xvf cmake-3.3.2-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.3.2-Linux-x86_64 cmake-install
  # add both the top-level directory and the bin directory from the archive
  # to the system PATH. By adding it to the front of the path we hide the
  # preinstalled CMake with our own.
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  # don't forget to switch back to the main build directory once you are done
  - cd ${TRAVIS_BUILD_DIR}
  - bash .travis/install_deps_lib_curl.sh
  - bash .travis/install_lib_curl.sh
script:
  - make check

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
