sudo: required
dist: xenial
language: go
go:
  - "1.11.x"

matrix:
  include:
    - os: linux
      env:
          - VERSION_UPGRADE_TEST_WAIT_TIMEOUT: 45s
          - ARCH: x86_64
          - ARCHGO: amd64
    - os: linux
      env:
        - VERSION_UPGRADE_TEST_WAIT_TIMEOUT: 45s
        - ARCH: i386
        - ARCHGO: 386
#    - os: osx
      # Do not start osx build for PR
#      if: type != pull_request
#      osx_image: xcode8
#      env: VERSION_UPGRADE_TEST_WAIT_TIMEOUT=60s
#      env: ARCH=x86_64

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq && sudo apt install qemu ; fi
  - eval "CC=gcc-6 && CXX=g++-6"

env:
  global:
    - BUILD_DIR: build
    - BUILDLIB_DIR: $BUILD_DIR/libskycoin
    - LIB_DIR: lib
    - CGO_ENABLED: 1

install:
  # Install gox
  - go get github.com/gz-c/gox
  - go get -t ./...
  - make install-linters
  # Install pinned golangci-lint, overriding the latest version install by make install-linters
  - VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh
  - ./ci-scripts/install-travis-gcc.sh
  - make install-deps-libc

script:
  - make lint
  # libskycoin tests
  - CC=gcc-6 make test-libc

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
