sudo: required
services:
  - docker
dist: trusty
language: go
go:
  - "1.11.x"

matrix:
  include:
    - os: linux
      env:
        - HW_EMU=orangepi-plus2
    - os: linux
      env:
        - HW_EMU=raspberry-pi2
    - os: linux
      env:
        - HW_EMU=raspberry-pi3
    - os: linux
      env:
        - HW_EMU=beaglebone-black
    - os: osx
      osx_image: xcode8

before_install:
  - VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh
  - ./ci-scripts/install-travis-gcc.sh

env:
  global:
    - BUILD_DIR: build
    - BUILDLIB_DIR: $BUILD_DIR/libskycoin
    - LIB_DIR: lib
    - CGO_ENABLED: 1
    - CC: gcc-6
    - CXX: g++-6
    - VERSION_UPGRADE_TEST_WAIT_TIMEOUT: 60s


install:
  # Install gox
  - go get github.com/gz-c/gox
  - go get -t ./...
  - make install-linters
  - VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh
  - make install-deps-libc

script:
  - make lint
  # # libskycoin tests
  - CC=gcc-6 make test-libc
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build --build-arg HW_EMU --build-arg OS_EMU=ubuntu . -t skydev-test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build --build-arg HW_EMU --build-arg OS_EMU=debian . -t skydev-test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build --build-arg HW_EMU --build-arg OS_EMU=fedora . -t skydev-test ; fi
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build --build-arg HW_EMU --build-arg OS_EMU . -t skydev-test ; fi

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
