sudo: required
dist: trusty
language: go
go:
  - "1.11.x"

matrix:
  include:
    - os: linux
      env: VERSION_UPGRADE_TEST_WAIT_TIMEOUT=45s
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
    - os: osx
      osx_image: xcode8
      env: VERSION_UPGRADE_TEST_WAIT_TIMEOUT=60s

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq; fi
  - VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh
  - ./ci-scripts/install-travis-gcc.sh
  - eval "CC=gcc-6 && CXX=g++-6"

env:
  global:
    - BUILD_DIR: build
    - BUILDLIB_DIR: $BUILD_DIR/libskycoin
    - LIB_DIR: lib
    - CGO_ENABLED: 1

before_install:
  # Ubuntu Trusty official package name is clang-format-3.4
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    PKG_CLANG_FORMAT=clang-format-7 ; else
    PKG_CLANG_FORMAT=clang-format ;
    fi

install:
  # Install gox
  - go get github.com/gz-c/gox
  - go get -t ./...
  # Install linters
  - make install-linters PKG_CLANG_FORMAT=$PKG_CLANG_FORMAT
  # Install pinned golangci-lint, overriding the latest version install by make install-linters
  - VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh
  # Install pinned golangci-lint, overriding the latest version install by make install-linters
  # - make install-deps-libc

script:
  - make lint
  # libskycoin tests
  - CC=gcc-6 make test-libc

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
