sudo: required
language: go
go:
  - "1.11.x"

matrix:
  include:
    - os: osx
      osx_image: xcode8.3

before_install:
  - ./ci-scripts/install-travis-gcc.sh
  - eval "CC=gcc-6 && CXX=g++-6"

env:
  global:
    - BUILD_DIR: build
    - BUILDLIB_DIR: $BUILD_DIR/libskycoin
    - LIB_DIR: lib
    - CGO_ENABLED: 1
    - VERSION_UPGRADE_TEST_WAIT_TIMEOUT: 60s
    - PATH_DIR: $GOPATH/src/github.com/skycoin/libskycoin/


install:
  -  go get github.com/gz-c/gox
  -  go get -t ./...
  -  make install-linters
  -  VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh
  -  make install-deps-libc
  -  make install-lib-curl

script:
  - make check

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
