sudo: required
services:
  - docker
dist: trusty
language: go
go:
  - "1.11.x"

matrix:
  include:
    - os: linux
      env: 
       - HW_EMU=X86
    - os: linux
      env: 
       - HW_EMU=orangepi-plus2
       - OS_EMU=debian
    - os: linux
      env: 
       - HW_EMU=orangepi-plus2
       - OS_EMU=ubuntu
    - os: linux
      env: 
       - HW_EMU=orangepi-plus2
       - OS_EMU=fedora
    - os: osx
      osx_image: xcode8

before_install:
  - if [[ "$HW_EMU" == "X86" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq; fi
  - if [[ "$HW_EMU" == "X86" ]]; then VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh; fi
  - if [[ "$HW_EMU" == "X86" ]]; then sh ./ci-scripts/install-travis-gcc.sh; fi

env:
  global:
    - BUILD_DIR: build
    - BUILDLIB_DIR: $BUILD_DIR/libskycoin
    - LIB_DIR: lib
    - CGO_ENABLED: 1
    - CC: gcc-6
    - CXX: g++-6
    - VERSION_UPGRADE_TEST_WAIT_TIMEOUT: 60s


install:
  # Install gox
  - if [[ "$HW_EMU" == "X86" || "$TRAVIS_OS_NAME" == 'osx' ]]; then go get github.com/gz-c/gox; fi
  - if [[ "$HW_EMU" == "X86" || "$TRAVIS_OS_NAME" == 'osx' ]]; then go get -t ./... ; fi
  - if [[ "$HW_EMU" == "X86" || "$TRAVIS_OS_NAME" == 'osx' ]]; then make install-linters ; fi
  - if [[ "$HW_EMU" == "X86" || "$TRAVIS_OS_NAME" == 'osx' ]]; then VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh ; fi
  # Install pinned golangci-lint, overriding the latest version install by make install-linters
  - if [[ "$HW_EMU" == "X86" || "$TRAVIS_OS_NAME" == 'osx' ]]; then make install-linters ; fi
  - if [[ "$HW_EMU" == "X86" || "$TRAVIS_OS_NAME" == 'osx' ]]; then make install-deps-libc ; fi

script:
  - if [[ "$HW_EMU" == "X86" || "$TRAVIS_OS_NAME" == 'osx' ]]; then make lint ; fi
  # # libskycoin tests
  - if [[ "$HW_EMU" == "X86" || "$TRAVIS_OS_NAME" == 'osx' ]]; then CC=gcc-6 make test-libc ; fi
  - if [["$HW_EMU" != "X86"]]; then docker build --build-arg HW_EMU --build-arg OS_EMU . -t skydev-test ; fi

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
