sudo: required
dist: trusty
language: go
go:
  - "1.11.x"

matrix:
  include:
    - os: linux
      env: VERSION_UPGRADE_TEST_WAIT_TIMEOUT=45s
    - os: osx
      osx_image: xcode8.3
      env: VERSION_UPGRADE_TEST_WAIT_TIMEOUT=60s

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq; fi
  - VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh
  - ./ci-scripts/install-travis-gcc.sh

env:
  global:
    - BUILD_DIR: build
    - BUILDLIB_DIR: $BUILD_DIR/libskycoin
    - LIB_DIR: lib
    - CGO_ENABLED: 1
    - CC: gcc-6
    - CXX: g++-6

install:
  # Install gox
  - go get github.com/gz-c/gox
  - go get -t ./...
  - make install-linters
  - VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh
  # Install pinned golangci-lint, overriding the latest version install by make install-linters
  - make install-deps-libc

script:
  - make lint
  # libskycoin tests
  - make test-libc

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
