sudo: required
services:
  - docker
dist: trusty
language: go
go:
  - "1.11.x"

matrix:
  include:
    - os: linux
    - os: linux
      env:
        - QEMU_PLATFORM=orangepi-plus2
        - QEMU_OS=ubuntu
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=orangepi-plus2
    #     - QEMU_OS=debian
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=orangepi-plus2
    #     - QEMU_OS=fedora
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=raspberry-pi2
    #     - QEMU_OS=ubuntu
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=raspberry-pi2
    #     - QEMU_OS=debian
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=raspberry-pi2
    #     - QEMU_OS=fedora
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=raspberrypi3
    #     - QEMU_OS=ubuntu
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=raspberrypi3
    #     - QEMU_OS=debian
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=raspberrypi3
    #     - QEMU_OS=fedora
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=beaglebone-black
    #     - QEMU_OS=ubuntu
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=beaglebone-black
    #     - QEMU_OS=debian
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=beaglebone-black
    #     - QEMU_OS=fedora
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=asus-tinker-board
    #     - QEMU_OS=ubuntu
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=asus-tinker-board
    #     - QEMU_OS=debian
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=asus-tinker-board
    #     - QEMU_OS=fedora
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=bananapi-m1-plus
    #     - QEMU_OS=ubuntu
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=bananapi-m1-plus
    #     - QEMU_OS=debian
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=bananapi-m1-plus
    #     - QEMU_OS=fedora
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=odroid-xu4
    #     - QEMU_OS=ubuntu
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=odroid-xu4
    #     - QEMU_OS=debian
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=odroid-xu4
    #     - QEMU_OS=fedora
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=odroid-c1
    #     - QEMU_OS=ubuntu
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=odroid-c1
    #     - QEMU_OS=debian
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=odroid-c1
    #     - QEMU_OS=fedora
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=odroid-xu4
    #     - QEMU_OS=ubuntu
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=odroid-xu4
    #     - QEMU_OS=debian
    # - os: linux
    #   env:
    #     - QEMU_PLATFORM=odroid-xu4
    #     - QEMU_OS=fedora
    - os: osx
      osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update -qq; fi
  - if [[ -z "$QEMU_PLATFORM" ]]; then ./ci-scripts/install-travis-gcc.sh ; fi

env:
  global:
    - BUILD_DIR: build
    - BUILDLIB_DIR: $BUILD_DIR/libskycoin
    - LIB_DIR: lib
    - CGO_ENABLED: 1
    - CC: gcc-6
    - CXX: g++-6
    - VERSION_UPGRADE_TEST_WAIT_TIMEOUT: 60s


install:
  # Install gox
  - go get github.com/gz-c/gox
  - go get -t ./...
  - make install-linters
  - VERSION=1.10.2 ./ci-scripts/install-golangci-lint.sh
  - make install-deps-libc

script:
  - make lint
  # # libskycoin tests
  - CC=gcc-6 make test-libc
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build --build-arg HW_EMU --build-arg OS_EMU . -t skydev-test ; fi

notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
