version: 2.1
jobs:
  linux_32bits:
    machine: true
    working_directory: $GOPATH/src/github.com/skycoin/libskycoin
    environment:
      BUILD_DIR: build
      BUILDLIB_DIR: $BUILD_DIR/libskycoin
      LIB_DIR: lib
      CGO_ENABLED: 1
      QEMU_PLATFORM: orangepi-plus2
      QEMU_OS: debian

    steps:
      - run: mkdir -p $GOPATH/src/github.com/ $GOPATH/src/github.com/skycoin
      - checkout
      - setup_remote_docker
      - run: docker build  --build-arg QEMU_PLATFORM --build-arg QEMU_OS --file $GOPATH/src/github.com/skycoin/libskycoin/docker/images/test-arm/Dockerfile  $GOPATH/src/github.com/skycoin/libskycoin -t skydev-test
      # - run: mkdir -p $GOPATH/src/github.com/skycoin
      # - run: cd $GOPATH/src/github.com/skycoin && git clone --branch v0.25.1 https://github.com/skycoin/skycoin 
      # - run: ls -oa $GOPATH/src/github.com/skycoin
      # - run: ls -oa $GOPATH/src/github.com/skycoin/libskycoin
      # - run: make -C $GOPATH/src/github.com/skycoin/libskycoin dep
      # - run: $GOPATH/src/github.com/skycoin/libskycoin/ci-scripts/install-travis-gcc.sh
      # - run: go get github.com/gz-c/gox
      # - run: go get -t ./...
      # - run: make -C $GOPATH/src/github.com/skycoin/libskycoin install-linters
      # - run: VERSION=1.10.2 $GOPATH/src/github.com/skycoin/libskycoin/ci-scripts/install-golangci-lint.sh
      # - run: make -C $GOPATH/src/github.com/skycoin/libskycoin install-deps-libc-linux
      # - run: make -C $GOPATH/src/github.com/skycoin/libskycoin install-lib-curl
      # - run: make -C $GOPATH/src/github.com/skycoin/libskycoin check

workflows:
  version: 2
  linux-osx:
    jobs:
      - linux_32bits


# - if [[ "$QEMU_PLATFORM" ]]; then docker build  --build-arg QEMU_PLATFORM --build-arg QEMU_OS --file docker/images/test-arm/Dockerfile  . -t skydev-test ; fi
